- name: Configuring Host name 
  ansible.builtin.shell: set-hostname {{tool_name}}

- name: Configuring the repo
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Installing ELK Stack
  ansible.builtin.dnf:
    name: 
      - elasticsearch
      - kibana 
      - logstash 
      - nginx 
    state: installed

- name: Configuring Reverse Proxy For Kibana
  ansible.builtin.template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Configuring Logstash Config
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Starting ELK Services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  loop: 
    - elasticsearch
    - kibana 
    - logstash 
    - nginx 

